from abc import ABC, abstractmethod
from decimal import Decimal
from typing import Optional, Protocol

from src.domain.entities import Account, Admin, Payment, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> Optional[User]: ...

    async def get_by_email(self, email: str) -> Optional[User]: ...

    async def create(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def delete(self, user_id: int) -> None: ...

    async def list_all(self) -> list[User]: ...


class AdminRepository(Protocol):
    async def get_by_id(self, admin_id: int) -> Optional[Admin]: ...

    async def get_by_email(self, email: str) -> Optional[Admin]: ...

    async def create(self, admin: Admin) -> Admin: ...


class AccountRepository(Protocol):
    async def get_by_id(self, account_id: int) -> Optional[Account]: ...

    async def get_by_user_id(self, user_id: int) -> list[Account]: ...

    async def create(self, account: Account) -> Account: ...

    async def add_balance(self, account_id: int, amount: Decimal) -> Account: ...


class PaymentRepository(Protocol):
    async def get_by_transaction_id(self, transaction_id: str) -> Optional[Payment]: ...

    async def create(self, payment: Payment) -> Payment: ...

    async def get_by_user_id(self, user_id: int) -> list[Payment]: ...


class UnitOfWork(ABC):
    @abstractmethod
    async def __aenter__(self): ...

    @abstractmethod
    async def __aexit__(self, *args): ...

    @property
    @abstractmethod
    def users(self) -> UserRepository: ...

    @property
    @abstractmethod
    def admins(self) -> AdminRepository: ...

    @property
    @abstractmethod
    def accounts(self) -> AccountRepository: ...

    @property
    @abstractmethod
    def payments(self) -> PaymentRepository: ...
